name: evently_plus
description: An independently maintained Flutter SDK for persistent event tracking and background-only analytics delivery.
version: 2.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

homepage: https://github.com/sina03030/evently_plus
repository: https://github.com/sina03030/evently_plus
issue_tracker: https://github.com/sina03030/evently_plus/issues

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  uuid: ^4.5.2
  workmanager: ^0.10.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
